escamboapp/config/routes.rb
Rails.application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'
  get 'backoffice', to: 'backoffice/dashboard#index'

  namespace :backoffice do
    resources :categories, except: [:show, :destroy]
    resources :admins, except: [:show]
    get 'dashboard', to: 'dashboard#index'
    resources :send_mail, only: [:edit, :create]
    resources :diagrams, only: [:index]
  end

  # get 'admin', to: 'backoffice/dashboard#index'

  namespace :site do

    get 'home', to: 'home#index'
    get 'search', to: 'search#ads'

    namespace :profile do
      resources :dashboard, only: [:index]
      resources :ads, only: [:index, :edit, :update, :new, :create]
      resources :my_data, only: [:edit, :update]
    end

    resources :ad_details, only: [:index, :show]
    resources :categories, only: [:show]
    resources :comments, only: [:create]
  end

  devise_for :admins, :skip => [:registrations]
  devise_for :members, controllers: { sessions: 'members/sessions',
                                                registrations:  'members/registrations'}

  root 'site/home#index'

end

escamboapp/app/models/ad.rb
class Ad < ActiveRecord::Base

  QTD_PER_PAGE = 6
  CAROUSEL_NUMBER = 3

  ratyrate_rateable "quality"

  # Callback Active Record
  before_save :md_to_html

  belongs_to :category, counter_cache: true
  belongs_to :member
  has_many :comments

  validates :title, :description_md, :description_short,
            :category, :picture, :finish_date, presence: true

  validates :price, numericality: { greater_than: 0 }

  monetize :price_cents

  has_attached_file :picture, styles: { large: "800x300#", medium: "320x150#", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\z/

  scope :last_six, -> { limit(QTD_PER_PAGE).order(created_at: :desc) }
  scope :descending_order, ->(page) { order(created_at: :desc).page(page).per(QTD_PER_PAGE) }
  scope :to_member, ->(member) { where(member: member) }
  scope :filter_category, -> (id, page) { where(category: id).page(page).per(QTD_PER_PAGE) }
  scope :search, -> (term, page) { where("title LIKE ?", "%#{term}%").page(page).per(QTD_PER_PAGE) }
  scope :carousel_random, -> { limit(CAROUSEL_NUMBER).order("RANDOM()")}


  def second
    self[1]
  end

  def third
    self[2]
  end

  private

    def md_to_html

      options = {
          filter_html: true,
          link_attributes: {
              rel: "nofollow",
              target: "_blank"
          }
      }

      extensions = {
          space_after_headers: true,
          autolink: true
      }

      renderer = Redcarpet::Render::HTML.new(options)
      markdown = Redcarpet::Markdown.new(renderer, extensions)

      self.description = markdown.render(self.description_md)

    end

end

escamboapp/app/models/admin.rb
class Admin < ActiveRecord::Base
  #Constants
  ROLES = {:full_access => 0, :restricted_access => 1}

  #Enums
  enum role: {:full_access => 0, :restricted_access => 1}

  #Scopes
  scope :with_full_access, -> { where(role: ROLES[:full_access]) }
  scope :with_restricted_access, -> { where(role: ROLES[:restricted_access]) }

  # def self.with_full_access
  #   where(role: 'full_access')
  # end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

escamboapp/app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "Member"
  belongs_to :rateable, :polymorphic => true
end

escamboapp/app/models/category.rb
class Category < ActiveRecord::Base

  extend FriendlyId

  friendly_id :description, use: :slugged

  has_many :ads

  validates_presence_of :description

  scope :order_by_description, -> { order(:description) }

  def to_param
    "#{id} #{description}".parameterize
  end


end

escamboapp/app/models/comment.rb
class Comment < ActiveRecord::Base

  belongs_to :member
  belongs_to :ad

end

escamboapp/app/models/member.rb
class Member < ActiveRecord::Base

  ratyrate_rater

  has_many :ads
  has_one :profile_member
  accepts_nested_attributes_for :profile_member

  validate :nested_attributes

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  def nested_attributes
   if nested_attributes_blank?
     errors.add(:base, "É necessário preencher os campo Nome e Sobrenome.")
   end
  end

  def nested_attributes_blank?
    profile_member.first_name.blank? || profile_member.last_name.blank?
  end
end

escamboapp/app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

escamboapp/app/models/profile_member.rb
class ProfileMember < ActiveRecord::Base

  belongs_to :member

  def full_name
    "#{self.first_name} #{self.last_name}"
  end

end

escamboapp/app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "Member"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

escamboapp/app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

escamboapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_filter :store_current_location, :unless => :devise_controller?

  protect_from_forgery with: :exception

  include Pundit

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  layout :layout_by_resource

  protected

  def layout_by_resource
    if devise_controller? && resource_name == :admin
      "backoffice_devise"
    elsif devise_controller? && resource_name == :member
      "site_devise"
    else
      "application"
    end
  end


  def user_not_authorized
    flash[:alert] = "Você não está autorizado a executar essa ação."
    redirect_to(request.referrer || root_path)
  end

  def after_sign_in_path_for(resource)

    if resource_name == :member

      stored_location = stored_location_for(resource)

      if stored_location.match(site_ad_details_path)
          stored_location
      else
        site_profile_dashboard_index_path(resource)
      end

    else
      backoffice_dashboard_path(resource)
    end

  end

  private

  def store_current_location
    store_location_for(:member, request.url)
  end
end

escamboapp/app/controllers/backoffice_controller.rb
class BackofficeController < ApplicationController

  before_action :authenticate_admin!

  layout 'backoffice'

  def pundit_user
    current_admin
  end

end

escamboapp/app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if member_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_f, current_member, params[:dimension]

      render :json => true
    else
      render :json => false
    end
  end
end

escamboapp/app/controllers/site_controller.rb
class SiteController < ApplicationController

  layout 'site'

end

escamboapp/app/helpers/ad_details_helper.rb
module AdDetailsHelper
end

escamboapp/app/helpers/application_helper.rb
module ApplicationHelper

  def current_user
    current_member
  end

  def devise_sign_in?
    params[:controller] == 'members/sessions' ? '' :'display:none'
  end


  def devise_sign_up?
    params[:controller] == 'members/registrations' ? '' :'display:none'
  end

end

escamboapp/app/helpers/site/categories_helper.rb
module Site::CategoriesHelper
end

escamboapp/app/helpers/site/comments_helper.rb
module Site::CommentsHelper
end

escamboapp/app/helpers/site/home_helper.rb
module Site::HomeHelper
end

escamboapp/app/helpers/site/search_helper.rb
module Site::SearchHelper
end

escamboapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Escamboapp</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<%= javascript_include_tag 'application'%>

</body>
</html>

escamboapp/app/views/layouts/backoffice.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>BackOffice - Escamboapp</title>

  <%= stylesheet_link_tag 'application', media: 'all'%>
  <%= stylesheet_link_tag 'backoffice', media: 'all'%>



  <%= csrf_meta_tags %>

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <![endif]-->

</head>

<body>

<div id="wrapper">

  <%= render partial: 'layouts/backoffice_shared/navigation' %>

  <!-- Page Content -->
  <div id="page-wrapper">
    <div class="container-fluid">
      <div class="row">
        <div class="col-lg-12">

          <%= yield %>

        </div>
      </div>
    </div>
  </div>
</div>

<%= javascript_include_tag 'application'%>
<%= javascript_include_tag 'backoffice'%>

<%= render partial: "layouts/shared/notifications" %>

</body>

</html>

escamboapp/app/views/layouts/backoffice_devise.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>BackOffice - Escamboapp</title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'backoffice', media: 'all', 'data-turbolinks-track' => true %>


  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'backoffice', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <![endif]-->

</head>
  <body>
    <%= yield %>
  </body>
</html>

escamboapp/app/views/layouts/profile.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Escamboapp</title>

  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= stylesheet_link_tag 'site', media: 'all' %>
  <%= stylesheet_link_tag 'site/profile', media: 'all' %>

  <%= yield :javascripts %>

  <%= csrf_meta_tags %>
</head>

<body>

<%= render partial: 'layouts/site_shared/navigation' %>

<div id="wrapper">

  <!-- Sidebar -->
  <div id="sidebar-wrapper">
    <ul class="sidebar-nav">

      <li class="sidebar-brand">
        <a href="#">
          Start Bootstrap
        </a>
      </li>

      <li>
        <%= link_to "Dashboard", site_profile_dashboard_index_path %>
      </li>

      <li>
        <%= link_to "Anúncios", site_profile_ads_path %>
      </li>

      <li>
        <%= link_to "Meus Dados", edit_site_profile_my_datum_path(current_member.id) %>
      </li>

    </ul>
  </div>

  <div id="page-content-wrapper">
    <div class="container-fluid">
      <div class="row">
        <div class="col-lg-12">
          <%= yield %>
        </div>
      </div>
    </div>
  </div>

</div>


<%= javascript_include_tag 'application' %>
<%= javascript_include_tag 'site' %>
<%= javascript_include_tag 'site/profile' %>
<%= javascript_include_tag 'site/profile/ads' %>

<%= render partial: "layouts/shared/notifications" %>

</body>


</html>

escamboapp/app/views/layouts/site.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Escamboapp</title>

  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= stylesheet_link_tag 'site', media: 'all' %>

  <%= csrf_meta_tags %>
</head>

<body>
<div id="global-spin" class="loading" style="display: none">Loading&#8230;</div>

<%= render partial: 'layouts/site_shared/navigation' %>

<div class="container">

  <!--   <p><%#= params %></p>-->
  <!--   <p><%#= controller_name %></p>-->
  <!--   <p><%#= controller_path %></p>-->

  <%= form_tag site_search_path, method: :get do %>

  <div class="row">
    <div class="well well-sm">
      <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">


          <div class="input-group">
            <%= text_field_tag(:q, params[:q], { class: 'form-control', placeholder: 'Pesquisar por...'}) %>
            <span class="input-group-btn">
              <%= submit_tag('Pesquisar', class: 'btn btn-primary') %>
              </span>
          </div>
        </div>
        <div class="col-lg-3"></div>
      </div>
    </div>
  </div>

  <% end %>

  <div class="row">

    <%= render partial: 'layouts/site_shared/sidebar' %>

    <div id="home-detail" class="col-md-9">

      <% if controller_path == 'site/home' %>
        <%= render partial: 'layouts/site_shared/carousel' %>
      <% end %>

      <div class="row">
        <%= yield %>
      </div>

    </div>

  </div>

</div>





<%= render partial: 'layouts/site_shared/footer' %>

<%= javascript_include_tag 'application' %>
<%= javascript_include_tag 'site' %>

<%= render partial: "layouts/shared/notifications" %>
</body>

</html>

escamboapp/app/views/layouts/site_devise.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>BackOffice - Escamboapp</title>

  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= stylesheet_link_tag    'site', media: 'all' %>

  <%= csrf_meta_tags %>

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <![endif]-->

</head>
<body>

<%= yield %>

<%= javascript_include_tag 'application' %>
<%= javascript_include_tag 'site' %>

</body>
</html>