escamboapp/config/routes.rb
Rails.application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'
  get 'backoffice', to: 'backoffice/dashboard#index'

  namespace :backoffice do
    resources :categories, except: [:show, :destroy]
    resources :admins, except: [:show]
    get 'dashboard', to: 'dashboard#index'
    resources :send_mail, only: [:edit, :create]
    resources :diagrams, only: [:index]
  end

  # get 'admin', to: 'backoffice/dashboard#index'

  namespace :site do

    get 'home', to: 'home#index'
    get 'search', to: 'search#ads'

    namespace :profile do
      resources :dashboard, only: [:index]
      resources :ads, only: [:index, :edit, :update, :new, :create]
      resources :my_data, only: [:edit, :update]
    end

    resources :ad_details, only: [:index, :show]
    resources :categories, only: [:show]
    resources :comments, only: [:create]
  end

  devise_for :admins, :skip => [:registrations]
  devise_for :members, controllers: { sessions: 'members/sessions',
                                                registrations:  'members/registrations'}

  root 'site/home#index'

end

escamboapp/app/models/ad.rb
class Ad < ActiveRecord::Base

  QTD_PER_PAGE = 6
  CAROUSEL_NUMBER = 3

  ratyrate_rateable "quality"

  # Callback Active Record
  before_save :md_to_html

  belongs_to :category, counter_cache: true
  belongs_to :member
  has_many :comments

  validates :title, :description_md, :description_short,
            :category, :picture, :finish_date, presence: true

  validates :price, numericality: { greater_than: 0 }

  monetize :price_cents

  has_attached_file :picture, styles: { large: "800x300#", medium: "320x150#", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\z/

  scope :last_six, -> { limit(QTD_PER_PAGE).order(created_at: :desc) }
  scope :descending_order, ->(page) { order(created_at: :desc).page(page).per(QTD_PER_PAGE) }
  scope :to_member, ->(member) { where(member: member) }
  scope :filter_category, -> (id, page) { where(category: id).page(page).per(QTD_PER_PAGE) }
  scope :search, -> (term, page) { where("title LIKE ?", "%#{term}%").page(page).per(QTD_PER_PAGE) }
  scope :carousel_random, -> { limit(CAROUSEL_NUMBER).order("RANDOM()")}


  def second
    self[1]
  end

  def third
    self[2]
  end

  private

    def md_to_html

      options = {
          filter_html: true,
          link_attributes: {
              rel: "nofollow",
              target: "_blank"
          }
      }

      extensions = {
          space_after_headers: true,
          autolink: true
      }

      renderer = Redcarpet::Render::HTML.new(options)
      markdown = Redcarpet::Markdown.new(renderer, extensions)

      self.description = markdown.render(self.description_md)

    end

end

escamboapp/app/controllers/site/profile/ads_controller.rb
class Site::Profile::AdsController < Site::ProfileController

  before_action :set_ad, only: [:edit, :update]

  def index
    @ads = Ad.to_member(current_member)
  end

  def new
    @ad = Ad.new
  end

  def create
    @ad = Ad.new(params_ad)
    @ad.member = current_member

    if @ad.save
      redirect_to site_profile_ads_path, notice: "Anúncio salvo com sucesso!"
    else
      render :new
    end
  end

  def edit

  end

  def update

    if @ad.update(params_ad)
      redirect_to site_profile_ads_path, notice: "Anúncio atualizado com sucesso!"
    else
      render :edit
    end
  end

  private

  def set_ad
    @ad = Ad.find(params[:id])
  end

  def params_ad
    params.require(:ad).permit(:id, :title, :description, :price,
                               :category_id, :member_id, :picture,
                               :finish_date, :description_md, :description_short)
  end

end

escamboapp/app/controllers/site/profile/dashboard_controller.rb
class Site::Profile::DashboardController < Site::ProfileController

  def index

  end

end

escamboapp/app/controllers/site/profile/my_data_controller.rb
class Site::Profile::MyDataController < Site::ProfileController

  before_action :set_member_profile, only: [:edit, :update]

  def edit

  end

  def update
    if @profile_member.update(params_profile_member)
      redirect_to edit_site_profile_my_datum_path(current_member.id), notice: "Perfil atualizado com sucesso!"
    else
      render :edit
    end

  end

  private

  def set_member_profile
    @profile_member = ProfileMember.find_or_create_by(member_id: current_member.id)
  end

  def params_profile_member
    params.require(:profile_member).permit(:id, :first_name, :last_name, :birthday)
  end


end

escamboapp/app/controllers/site/profile_controller.rb
class Site::ProfileController < SiteController

  layout 'profile'

end

escamboapp/app/helpers/site/profile/ads_helper.rb
module Site::Profile::AdsHelper
end

escamboapp/app/helpers/site/profile/dashboard_helper.rb
module Site::Profile::DashboardHelper
end

escamboapp/app/helpers/site/profile/my_data_helper.rb
module Site::Profile::MyDataHelper
end

escamboapp/app/views/site/profile/ads/edit.html.erb
<%= render partial: "site/profile/ads/shared/form", locals: {action: "Editando Anúncio", label_button: "Atualizar"} %>

escamboapp/app/views/site/profile/ads/index.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="page-header"> Anúncios </h3>

    <div class="row">
      <div class="col-lg-12" align="right">
        <%= link_to new_site_profile_ad_path, class: "btn btn-success" do %>
          <i class="fa fa-plus"></i> &nbsp;Novo
        <% end %>
      </div>
    </div>

  </div>

  <div class="panel-body">
    <div class="table-responsive">
      <table class="table table-striped table-bordered table-hover">
        <thead>
        <tr>
          <th>#</th>
          <th>Titulo</th>
          <th>Categoria</th>
          <th>Preço</th>
          <th>Imagem</th>
          <th style="width: 150px;">Ações</th>
        </tr>
        </thead>
        <tbody>
        <% @ads.each do |ad| %>
          <tr>
            <td><%= ad.id %></td>
            <td><%= ad.title %></td>
            <td><%= ad.category.description %></td>
            <td><%= humanized_money_with_symbol ad.price %></td>
            <td><%= image_tag ad.picture.url(:thumb) %></td>

            <td>
              <%= link_to edit_site_profile_ad_path(ad.id), class: "btn btn-warning btn-circle", tooltype: "Editar"  do %>
                <i class="fa fa-edit"></i>
              <% end %>
              <button type="button" class="btn btn-danger btn-circle"><i class="fa fa-times"></i>
              </button>
            </td>
          </tr>
        <% end %>

        </tbody>
      </table>
    </div>
  </div>
</div>

escamboapp/app/views/site/profile/ads/new.html.erb
<%= render partial: "site/profile/ads/shared/form", locals: {action: "Novo Anúncio", label_button: "Salvar"} %>