escamboapp/config/routes.rb
Rails.application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'
  get 'backoffice', to: 'backoffice/dashboard#index'

  namespace :backoffice do
    resources :categories, except: [:show, :destroy]
    resources :admins, except: [:show]
    get 'dashboard', to: 'dashboard#index'
    resources :send_mail, only: [:edit, :create]
    resources :diagrams, only: [:index]
  end

  # get 'admin', to: 'backoffice/dashboard#index'

  namespace :site do

    get 'home', to: 'home#index'
    get 'search', to: 'search#ads'

    namespace :profile do
      resources :dashboard, only: [:index]
      resources :ads, only: [:index, :edit, :update, :new, :create]
      resources :my_data, only: [:edit, :update]
    end

    resources :ad_details, only: [:index, :show]
    resources :categories, only: [:show]
    resources :comments, only: [:create]
  end

  devise_for :admins, :skip => [:registrations]
  devise_for :members, controllers: { sessions: 'members/sessions',
                                                registrations:  'members/registrations'}

  root 'site/home#index'

end

escamboapp/app/controllers/site/ad_details_controller.rb
class Site::AdDetailsController < SiteController

  def show
    @categories = Category.order_by_description
    @ad = Ad.find(params[:id])
  end
end

escamboapp/app/controllers/site/categories_controller.rb
class Site::CategoriesController < SiteController

  def show
    @categories = Category.order_by_description
    @category = Category.friendly.find(params[:id])
    @ads = Ad.filter_category(@category, params[:page])
  end
end

escamboapp/app/controllers/site/comments_controller.rb
class Site::CommentsController < ApplicationController

  before_action :authenticate_member!

  def create
    @comment = Comment.new(comment_params)
    @comment.member = current_member

    if @comment.save
      redirect_to site_ad_detail_path(@comment.ad_id), notice: "Comentário realizado com sucesso."
    else
      redirect_to site_ad_detail_path(@comment.ad_id), notice: "Erro ao adicionar o comentário."
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body, :ad_id)
  end
end

escamboapp/app/controllers/site/home_controller.rb
class Site::HomeController < SiteController

  def index
    @categories = Category.order_by_description
    @ads = Ad.descending_order(params[:page])
    @carousel = Ad.carousel_random()
  end
end

escamboapp/app/controllers/site/profile/ads_controller.rb
class Site::Profile::AdsController < Site::ProfileController

  before_action :set_ad, only: [:edit, :update]

  def index
    @ads = Ad.to_member(current_member)
  end

  def new
    @ad = Ad.new
  end

  def create
    @ad = Ad.new(params_ad)
    @ad.member = current_member

    if @ad.save
      redirect_to site_profile_ads_path, notice: "Anúncio salvo com sucesso!"
    else
      render :new
    end
  end

  def edit

  end

  def update

    if @ad.update(params_ad)
      redirect_to site_profile_ads_path, notice: "Anúncio atualizado com sucesso!"
    else
      render :edit
    end
  end

  private

  def set_ad
    @ad = Ad.find(params[:id])
  end

  def params_ad
    params.require(:ad).permit(:id, :title, :description, :price,
                               :category_id, :member_id, :picture,
                               :finish_date, :description_md, :description_short)
  end

end

escamboapp/app/controllers/site/profile/dashboard_controller.rb
class Site::Profile::DashboardController < Site::ProfileController

  def index

  end

end

escamboapp/app/controllers/site/profile/my_data_controller.rb
class Site::Profile::MyDataController < Site::ProfileController

  before_action :set_member_profile, only: [:edit, :update]

  def edit

  end

  def update
    if @profile_member.update(params_profile_member)
      redirect_to edit_site_profile_my_datum_path(current_member.id), notice: "Perfil atualizado com sucesso!"
    else
      render :edit
    end

  end

  private

  def set_member_profile
    @profile_member = ProfileMember.find_or_create_by(member_id: current_member.id)
  end

  def params_profile_member
    params.require(:profile_member).permit(:id, :first_name, :last_name, :birthday)
  end


end

escamboapp/app/controllers/site/profile_controller.rb
class Site::ProfileController < SiteController

  layout 'profile'

end

escamboapp/app/controllers/site/search_controller.rb
class Site::SearchController < SiteController

  def ads
    @categories = Category.order_by_description
    @ads = Ad.search(params[:q], params[:page])
  end
end

escamboapp/app/controllers/site_controller.rb
class SiteController < ApplicationController

  layout 'site'

end

escamboapp/app/helpers/ad_details_helper.rb
module AdDetailsHelper
end

escamboapp/app/helpers/site/categories_helper.rb
module Site::CategoriesHelper
end

escamboapp/app/helpers/site/comments_helper.rb
module Site::CommentsHelper
end

escamboapp/app/helpers/site/home_helper.rb
module Site::HomeHelper
end

escamboapp/app/helpers/site/profile/ads_helper.rb
module Site::Profile::AdsHelper
end

escamboapp/app/helpers/site/profile/dashboard_helper.rb
module Site::Profile::DashboardHelper
end

escamboapp/app/helpers/site/profile/my_data_helper.rb
module Site::Profile::MyDataHelper
end

escamboapp/app/helpers/site/search_helper.rb
module Site::SearchHelper
end

escamboapp/app/views/site/ad_details/_ad.html.erb
<div class="thumbnail">

  <%= image_tag @ad.picture.url(:large), class: "img-responsive" %>
  <div class="caption-full">
    <h4 class="pull-right"><%= humanized_money_with_symbol @ad.price %></h4>
    <h4><%= @ad.title %></h4>
    <p>
      <%= @ad.description.html_safe %>
    </p>
  </div>
  <div class="ratings">
    <p class="pull-right">3 reviews</p>
    <p>
      <span class="glyphicon glyphicon-star"></span>
      <span class="glyphicon glyphicon-star"></span>
      <span class="glyphicon glyphicon-star"></span>
      <span class="glyphicon glyphicon-star"></span>
      <span class="glyphicon glyphicon-star-empty"></span>
      4.0 stars
    </p>
  </div>
</div>

<div class="well">

  <div class="text-right">
    <a class="btn btn-success">Leave a Review</a>
  </div>

  <hr>

  <div class="row">
    <div class="col-md-12">
      <span class="glyphicon glyphicon-star"></span>
      <span class="glyphicon glyphicon-star"></span>
      <span class="glyphicon glyphicon-star"></span>
      <span class="glyphicon glyphicon-star"></span>
      <span class="glyphicon glyphicon-star-empty"></span>
      Anonymous
      <span class="pull-right">10 days ago</span>
      <p>This product was great in terms of quality. I would definitely buy another!</p>
    </div>
  </div>

  <hr>

  <div class="row">
    <div class="col-md-12">
      <span class="glyphicon glyphicon-star"></span>
      <span class="glyphicon glyphicon-star"></span>
      <span class="glyphicon glyphicon-star"></span>
      <span class="glyphicon glyphicon-star"></span>
      <span class="glyphicon glyphicon-star-empty"></span>
      Anonymous
      <span class="pull-right">12 days ago</span>
      <p>I've alredy ordered another one!</p>
    </div>
  </div>

  <hr>

  <div class="row">
    <div class="col-md-12">
      <span class="glyphicon glyphicon-star"></span>
      <span class="glyphicon glyphicon-star"></span>
      <span class="glyphicon glyphicon-star"></span>
      <span class="glyphicon glyphicon-star"></span>
      <span class="glyphicon glyphicon-star-empty"></span>
      Anonymous
      <span class="pull-right">15 days ago</span>
      <p>I've seen some better than this, but not at this price. I definitely recommend this item.</p>
    </div>
  </div>

</div>

escamboapp/app/views/site/ad_details/_comment_modal.html.erb
<%= form_tag site_comments_path do %>
  <div class="modal fade" id="commentModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">

        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="myModalLabel">Deixe seu comentário...</h4>
        </div>

        <div class="modal-body">

          <div class="form-group">

            <label>Comentário</label>
            <%= text_area :comment, :body, class:"form-control", rows: 10 %>
            <%= hidden_field :comment, :ad_id, value: @ad.id %>
          </div>

        </div>

        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
          <%= submit_tag "Enviar", class: "btn btn-primary" %>
        </div>

      </div>
    </div>
  </div>
<% end %>

escamboapp/app/views/site/ad_details/_comments.html.erb
<% @ad.comments.each do |comment| %>
<div class="row">
  <div class="col-md-12">
    <span class="glyphicon glyphicon-star"></span>
    <span class="glyphicon glyphicon-star"></span>
    <span class="glyphicon glyphicon-star"></span>
    <span class="glyphicon glyphicon-star"></span>
    <span class="glyphicon glyphicon-star-empty"></span>
    <%= comment.member.email %>
    <span class="pull-right"><%= time_ago_in_words(comment.created_at) %></span>

    <p><%= comment.body %></p>

    <% if (current_member) && comment.member.id == current_member.id%>
      <%= rating_for_user @ad, current_member, 'quality'%>
    <% end %>
  </div>
</div>

<hr>

<% end %>

escamboapp/app/views/site/ad_details/_show.html.erb
<div class="thumbnail">

  <%= image_tag @ad.picture.url(:large), class: "img-responsive" %>
  <div class="caption-full">
    <h4 class="pull-right"><%= humanized_money_with_symbol @ad.price %></h4>
    <h4><%= @ad.title %></h4>
    <p>
      <%= @ad.description.html_safe %>
    </p>
  </div>


    <div class="well well-sm">
      <div class="ratings">
        <%= rating_for @ad, 'quality' %>
        <p class="pull-right"><%= @ad.rates('quality').count %>&nbsp;<%= t('labels.reviews') %></p>
        </p>
      </div>
    </div>

</div>

<div class="well">

  <% if member_signed_in?  %>
    <div class="text-right">
      <button type="button" class="btn btn-success" data-toggle="modal" data-target="#commentModal">
        Deixe um comentário
      </button>
    </div>
  <% else %>
    <div class="text-right">
      <%= link_to "Logar para comentar", new_member_session_path, class: "btn btn-success"  %>
    </div>
  <%end%>

  <hr>

  <%= render partial: "site/ad_details/comments" %>

</div>

<%= render partial: "site/ad_details/comment_modal" %>

escamboapp/app/views/site/ad_details/show.html.erb
<%= render partial: 'site/ad_details/show' %>

escamboapp/app/views/site/ad_details/show.js.erb
<%#= render 'site/ad_details/show' %>